### ISSUE TITLE
Nmap  shows unnecessary error in result

### ISSUE THREAD

**Issue by R1w** [nmap/nmap#1287]
nmap/bionic,now 7.60-1ubuntu5 amd64
Running this command "nmap -sV --script=banner A.A.A.A  -A" and in result there are hundreds of unnecessary line of error  as shows in result:
```
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
NSOCK ERROR [0.8960s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #1): Protocol not available (92)
NSOCK ERROR [0.8970s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #2): Protocol not available (92)
NSOCK ERROR [0.8970s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #3): Protocol not available (92)
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
NSOCK ERROR [36.4930s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #1): Protocol not available (92)
NSOCK ERROR [36.5040s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #2): Protocol not available (92)
NSOCK ERROR [36.5070s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #3): Protocol not available (92)
NSOCK ERROR [36.5100s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #4): Protocol not available (92)
NSOCK ERROR [36.5130s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #5): Protocol not available (92)
```
These problem should be fix because the result could be much more faster if it get fiexed.

**Comment by dmiller-nmap** [comment]
These lines are output because there is something wrong with what Nmap is trying to do. Can you please provide some more info for us to diagnose?

1. Output of `nmap --version`
2. Output of `uname -a`
3. Output of `nmap --iflist`
4. Output of `nmap --route-dst A.A.A.A` for your target.
5. Does your scan work apart from the error output, or is the result other than what you expected?

**Comment by R1w** [comment]
I did test the same command in 4 different Linux distro with different Nmap version ,but the result is similar , i mean "unnecessary error" .

1. Output of `nmap --version`
Nmap version 7.70
2. Output of `uname -a`
Linux   4.4.0-17134-Microsoft #81-Microsoft Sun May 20 01:14:00 PST 2018 x86_64 GNU/Linux
3. Output of `nmap --iflist`
Starting Nmap 7.70 ( https://nmap.org ) at 2018-08-07 10:12 DST
************************INTERFACES************************
DEV  (SHORT) IP/MASK       TYPE     UP MTU  MAC
eth0 (eth0)  X.X.X.X/25 ethernet up 1500 X:X:X:X:X:X
lo   (lo)    127.0.0.1/8   loopback up 1500
lo   (lo)    ::1/128       loopback up 1500
**************************ROUTES**************************
DST/MASK           DEV  METRIC GATEWAY
0.0.0.0/32         eth0 0       X.X.X.X
 X.X.X.X /32      eth0 256
X.X.X.X /32    eth0 256
255.255.255.255/32 eth0 256
127.0.0.1/32       lo   256
127.255.255.255/32 lo   256
255.255.255.255/32 lo   256
172.17.3.0/25      eth0 256
127.0.0.0/8        lo   256
224.0.0.0/4        eth0 256
224.0.0.0/4        lo   256
::1/128            lo   256
ff00::/8           lo   256
4. Output of `nmap --route-dst A.A.A.A`
Starting Nmap 7.70 ( https://nmap.org ) at 2018-08-07 10:18 DST
X.X.X.X
eth0 eth0 srcaddr X.X.X.X nexthop X.X.X.X
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.06 seconds.
5. Scan Does work correctly.

**Comment by dmiller-nmap** [comment]
You are using Nmap on the Windows Subsystem for Linux (WSL). This is a partial emulation of Linux on Windows and does not support all features of the Linux kernel. In this case, Nmap expects to use `setsockopt` with `SO_BINDTODEVICE`, which is not supported in WSL.

Nmap is fully supported as a native Windows application. Please download the latest installer from https://nmap.org/download.html#windows to get started.

If you want Nmap to work on WSL, you can comment on the specific issue with that repo: Microsoft/WSL#3440

**Comment by bakialmaci** [comment]
Is there any Update for WSL

**Comment by iamnotagentleman** [comment]
it's fixed with WSL2

**Comment by fyodor** [comment]
Thanks for the update.  I'm glad to hear that it's fixed with WSL2.

**Comment by vespasianthesubguest** [comment]
> 
> 
> it's fixed with WSL2

I've installed kali for windows 10 only last week. Ran the updates, and installed nmap. I am still getting the same error as dmiller-nmap above 
@dmiller-nmap dmiller-nmap mentioned this issue on Jul 9, 2019
dnet: Failed to open device eth0 QUITTING!

how do I check I'm running WSL2? i've tried wsl -l -v but it just lists instructions on how to use the wsl command and the arguments/options etc

**Comment by 0xR0b07-c47** [comment]
> > it's fixed with WSL2
> 
> I've installed kali for windows 10 only last week. Ran the updates, and installed nmap. I am still getting the same error as dmiller-nmap above @dmiller-nmap dmiller-nmap mentioned this issue on Jul 9, 2019 dnet: Failed to open device eth0 QUITTING!
> 
> how do I check I'm running WSL2? i've tried wsl -l -v but it just lists instructions on how to use the wsl command and the arguments/options etc

https://winaero.com/install-windows-subsystem-for-linux-2-in-windows-10/

**Comment by Zswdhy** [comment]
Warning: Nmap may not work correctly on Windows Subsystem for Linux.
For best performance and accuracy, use the native Windows build from https://nmap.org/download.html#windows.
Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.6 openssl-3.0.2 nmap-libssh2-1.8.2 libz-1.2.11 libpcre-8.39 libpcap-1.10.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
