### ISSUE TITLE
npcap capture on loopback adaptor shows extra bytes on the wire

### ISSUE THREAD

**Issue by gbloice** [nmap/nmap#1524]
When using Wireshark and npcap to capture on the npcap loopback adaptor, each packet appears to have extra bytes in the capture, e.g.

`Frame 1: 134 bytes on wire (1072 bits), 74 bytes captured (592 bits) on interface 0`

In the above frame there are only 74 bytes of data.

**Comment by dmiller-nmap** [comment]
Thanks for the report! I'm not seeing the problem here, but I know we changed around the code surrounding packet filtering and copying into the ring buffer in 0.992, so maybe we fixed this without knowing about it.

* Does this happen with every frame, or only some of them?
* What version of Npcap are you using?
* Does it happen with Npcap 0.992?

**Comment by gbloice** [comment]
Installing 0.992 after previously having 0.991 and 0.99r9 caused me to have multiple Npcap loopback adaptors:

```
> Get-NetAdapter

Name                    InterfaceDescription    MacAddress       
----                    --------------------    ----------       
Npcap Loopback Adapter  Npcap Loopback Adapter  02-00-4C-4F-4F-50
Ethernet 2              Npcap Loopback Adapter  02-00-4C-4F-4F-50
Ethernet 3              Npcap Loopback Adapter  02-00-4C-4F-4F-50
```

I shall try uninstalling npcap, possibly manually deleting the extra adaptors and see where we are.

**Comment by gbloice** [comment]
Following on:

1. Uninstalled npcap.  This left the top 2 adaptors listed in my post still present.  Manually deleted those from Device Manager.
1. Rebooted.
1. Reinstalled 0.992.

Now I only have the one loopback adaptor and capturing on it produces sensible results, so this issue seems to have been fixed.

There does seem to be another issue with npcap creating extra loopback adaptors and then an uninstall not cleaning them all up.
