### ISSUE TITLE
Assertion failed: (res > 7), function nsock_library_initialize

### ISSUE THREAD

**Issue by alexfunnell** [nmap/nmap#2081]
**The bug**

Getting this error on nmap 7.80.

(base) Alexs-MacBook-Pro:~ vulcan$ nmap -T4 -A -v 192.168.1.2
Starting Nmap 7.80 ( https://nmap.org ) at 2020-07-14 11:47 BST
Assertion failed: (res > 7), function nsock_library_initialize, file nsock_pool.c, line 307.
Abort trap: 6

**To Reproduce**. 
I believe this may be an error with MacOS 11 Big Sur. I'm using MacOS Version 11.0 Beta (20A4299v).

**Version info (please complete the following information):**
 - OS: MacOS Version 11.0 Beta (20A4299v)
 - Output of `nmap --version`: 

```
Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-apple-darwin17.7.0
Compiled with: nmap-liblua-5.3.5 openssl-1.0.2s nmap-libssh2-1.8.2 libz-1.2.11 nmap-libpcre-7.6 nmap-libpcap-1.9.0 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: kqueue poll select
```

 - Output of `nmap --iflist`:

```
Starting Nmap 7.80 ( https://nmap.org ) at 2020-07-14 11:53 BST
************************INTERFACES************************
DEV     (SHORT)   IP/MASK                       TYPE        UP   MTU   MAC
lo0     (lo0)     127.0.0.1/8                   loopback    up   16384
lo0     (lo0)     ::1/128                       loopback    up   16384
lo0     (lo0)     fe80::1/128                   loopback    up   16384
lo0     (lo0)     127.94.0.1/8                  loopback    up   16384
gif0    (gif0)    (none)/0                      point2point down 1280
stf0    (stf0)    (none)/0                      other       down 1280
en0     (en0)     192.168.1.73/24               ethernet    up   1500  4C:32:75:94:72:2D
en1     (en1)     (none)/0                      ethernet    up   1500  82:17:0B:6D:A7:40
en2     (en2)     (none)/0                      ethernet    up   1500  82:17:0B:6D:A7:41
bridge0 (bridge0) (none)/0                      ethernet    up   1500  82:17:0B:6D:A7:40
p2p0    (p2p0)    (none)/0                      ethernet    up   2304  0E:32:75:94:72:2D
awdl0   (awdl0)   (none)/0                      ethernet    up   1484  02:96:14:6E:EF:9B
awdl0   (awdl0)   fe80::96:14ff:fe6e:ef9b/128   ethernet    up   1484  02:96:14:6E:EF:9B
llw0    (llw0)    (none)/0                      ethernet    up   1500  02:96:14:6E:EF:9B
llw0    (llw0)    fe80::96:14ff:fe6e:ef9b/128   ethernet    up   1500  02:96:14:6E:EF:9B
utun0   (utun0)   (none)/0                      point2point up   1380
utun0   (utun0)   fe80::d78c:468e:151a:244/128  point2point up   1380
utun1   (utun1)   (none)/0                      point2point up   2000
utun1   (utun1)   fe80::fc13:abf0:c3b3:2bfc/128 point2point up   2000
utun2   (utun2)   (none)/0                      point2point up   1380
utun2   (utun2)   fe80::c2d4:b620:569:a90e/128  point2point up   1380
utun3   (utun3)   (none)/0                      point2point up   1380
utun3   (utun3)   fe80::91d1:5cb2:6d4:376c/128  point2point up   1380

**************************ROUTES**************************
DST/MASK                        DEV   METRIC GATEWAY
172.217.169.42/32               en0   0      192.168.1.1
216.58.210.46/32                en0   0      192.168.1.1
192.168.1.1/32                  en0   0
192.168.1.73/32                 en0   0
2.20.92.9/32                    en0   0      192.168.1.1
199.232.54.208/32               en0   0      192.168.1.1
2.21.75.27/32                   en0   0      192.168.1.1
204.79.197.200/32               en0   0      192.168.1.1
2.21.75.59/32                   en0   0      192.168.1.1
13.227.171.225/32               en0   0      192.168.1.1
17.56.10.21/32                  en0   0      192.168.1.1
17.56.138.24/32                 en0   0      192.168.1.1
17.57.146.148/32                en0   0      192.168.1.1
17.57.146.149/32                en0   0      192.168.1.1
17.248.149.113/32               en0   0      192.168.1.1
17.248.149.133/32               en0   0      192.168.1.1
17.248.178.69/32                en0   0      192.168.1.1
17.253.77.201/32                en0   0      192.168.1.1
17.253.77.203/32                en0   0      192.168.1.1
18.203.147.187/32               en0   0      192.168.1.1
20.190.129.128/32               en0   0      192.168.1.1
34.196.246.152/32               en0   0      192.168.1.1
40.67.251.132/32                en0   0      192.168.1.1
40.100.174.194/32               en0   0      192.168.1.1
51.141.8.249/32                 en0   0      192.168.1.1
52.97.146.130/32                en0   0      192.168.1.1
52.97.179.226/32                en0   0      192.168.1.1
52.206.227.240/32               en0   0      192.168.1.1
64.233.167.189/32               en0   0      192.168.1.1
69.171.250.63/32                en0   0      192.168.1.1
74.125.133.155/32               en0   0      192.168.1.1
93.184.220.29/32                en0   0      192.168.1.1
127.0.0.1/32                    lo0   0      127.0.0.1
127.94.0.1/32                   lo0   0      127.94.0.1
130.211.16.53/32                en0   0      192.168.1.1
136.243.95.144/32               en0   0      192.168.1.1
138.201.149.0/32                en0   0      192.168.1.1
140.82.113.25/32                en0   0      192.168.1.1
140.82.118.3/32                 en0   0      192.168.1.1
140.82.118.4/32                 en0   0      192.168.1.1
140.82.118.5/32                 en0   0      192.168.1.1
140.82.118.6/32                 en0   0      192.168.1.1
151.101.0.133/32                en0   0      192.168.1.1
151.101.1.181/32                en0   0      192.168.1.1
151.101.64.133/32               en0   0      192.168.1.1
151.101.128.133/32              en0   0      192.168.1.1
151.101.192.133/32              en0   0      192.168.1.1
151.139.128.14/32               en0   0      192.168.1.1
157.240.221.63/32               en0   0      192.168.1.1
157.240.221.174/32              en0   0      192.168.1.1
172.217.169.14/32               en0   0      192.168.1.1
172.217.169.46/32               en0   0      192.168.1.1
185.199.109.154/32              en0   0      192.168.1.1
185.199.110.154/32              en0   0      192.168.1.1
1.1.1.1/32                      en0   0      192.168.1.1
2.20.92.160/32                  en0   0      192.168.1.1
2.21.75.51/32                   en0   0      192.168.1.1
13.227.171.15/32                en0   0      192.168.1.1
204.79.197.219/32               en0   0      192.168.1.1
216.58.198.174/32               en0   0      192.168.1.1
216.58.204.46/32                en0   0      192.168.1.1
216.58.205.46/32                en0   0      192.168.1.1
216.58.206.97/32                en0   0      192.168.1.1
1.0.0.1/32                      en0   0      192.168.1.1
216.58.212.195/32               en0   0      192.168.1.1
216.58.212.206/32               en0   0      192.168.1.1
216.58.212.225/32               en0   0      192.168.1.1
216.58.212.238/32               en0   0      192.168.1.1
216.58.213.14/32                en0   0      192.168.1.1
255.255.255.255/32              en0   0
192.168.1.0/24                  en0   0
169.254.0.0/16                  en0   0
127.0.0.0/8                     lo0   0      127.0.0.1
224.0.0.0/4                     en0   0
0.0.0.0/0                       en0   0      192.168.1.1
::1/128                         lo0   0      ::1
fe80:1::1/128                   lo0   0
fe80:b::d78c:468e:151a:244/128  lo0   0
fe80:c::fc13:abf0:c3b3:2bfc/128 lo0   0
fe80:d::4eef:9bf4:87fc:c5f3/128 utun2 0      fe80:d::c2d4:b620:569:a90e
fe80:d::c2d4:b620:569:a90e/128  lo0   0
fe80:e::91d1:5cb2:6d4:376c/128  lo0   0
fe80:1::/64                     lo0   0      fe80:1::1
fe80:9::/64                     awdl0 0
fe80:a::/64                     llw0  0
fe80:b::/64                     utun0 0      fe80:b::d78c:468e:151a:244
fe80:c::/64                     utun1 0      fe80:c::fc13:abf0:c3b3:2bfc
fe80:d::/64                     utun2 0      fe80:d::c2d4:b620:569:a90e
fe80:e::/64                     utun3 0      fe80:e::91d1:5cb2:6d4:376c
ff01:1::/32                     lo0   0      ::1
ff01:9::/32                     awdl0 0
ff01:a::/32                     llw0  0
ff01:b::/32                     utun0 0      fe80:b::d78c:468e:151a:244
ff01:c::/32                     utun1 0      fe80:c::fc13:abf0:c3b3:2bfc
ff01:d::/32                     utun2 0      fe80:d::c2d4:b620:569:a90e
ff01:e::/32                     utun3 0      fe80:e::91d1:5cb2:6d4:376c
ff02:1::/32                     lo0   0      ::1
ff02:9::/32                     awdl0 0
ff02:a::/32                     llw0  0
ff02:b::/32                     utun0 0      fe80:b::d78c:468e:151a:244
ff02:c::/32                     utun1 0      fe80:c::fc13:abf0:c3b3:2bfc
ff02:d::/32                     utun2 0      fe80:d::c2d4:b620:569:a90e
ff02:e::/32                     utun3 0      fe80:e::91d1:5cb2:6d4:376c
::/0                            utun0 0      fe80:b::
::/0                            utun1 0      fe80:c::
::/0                            utun2 0      fe80:d::
::/0                            utun3 0      fe80:e::

```

**Comment by dmiller-nmap** [comment]
I fixed this in b41c39ea78ac9337a741fd942ef3df3a0dea3156 at the end of June based on a report I saw on Twitter, but I forgot to reply there or put it in the changelog. I think this only affects homebrew builds at the moment.

**Comment by AlfGalf** [comment]
@dmiller-nmap I compiled that commit but am still getting the same issue in BigSur

**Comment by dmiller-nmap** [comment]
This fix was incomplete.  See #2079 for complete discussion and final fix, which is included in Nmap 7.91.

**Comment by yogi-breh** [comment]
Experiencing same issue on Nmap 7.91 - Install via home-brew on MacOS Big Sur 11.0.1

**Comment by levydanqc** [comment]
Also experiencing this issue, but on Ncrack...
" Starting Ncrack 0.7 ( http://ncrack.org ) at 2020-12-07 19:55 EST
Assertion failed: (res > 7), function nsock_library_initialize, file nsock_pool.c, line 307.
zsh: abort "

**Comment by peterclauterbach** [comment]
> Experiencing same issue on Nmap 7.91 - Install via home-brew on MacOS Big Sur 11.0.1

I had similar issue; somehow had two version of nmap installed, and older one in /usr/local/bin (nmap 7.8) and the latest one in /usr/local/opt/nmap (nmap 7.91).  Not sure how that happened, it's was a while since I updated homebrew.  A "brew doctor" caught the issue, and "brew link nmap" fixed it.

**Comment by njma710** [comment]
اوك

في الأربعاء، ٢٣ ديسمبر ٢٠٢٠ ٦:٣٢ م peterclauterbach <
notifications@github.com> كتب:

**Comment by Aholicknight** [comment]
Had the same problem on my mac. I first did `brew link nmap` and that did nothing. It showed an error saying:
```
Target /usr/local/bin/ncat
already exists. You may want to remove it:
  rm '/usr/local/bin/ncat'

To force the link and overwrite all conflicting files:
  brew link --overwrite nmap
```
Then I ran `brew link --overwrite nmap` and then another error showed up:
```
Linking /usr/local/Cellar/nmap/7.91... 
Error: Could not symlink share/man/de/man1/nmap.1
/usr/local/share/man/de/man1 is not writable.

```
How can I fix? Even when uninstalling nmap and reinstalling does not fix.

**Comment by haidangwa** [comment]
@Aholicknight I had the same issue, but it resolved for me after I found that the `brew install nmap` placed everything in /usr/local/Cellar/nmap. I symlinked it to /usr/local/bin/nmap which is in my path.

```
ln -s /usr/local/Cellar/nmap/7.92/bin/nmap /usr/local/bin/nmap
```

**Comment by parcivad** [comment]
@haidangwa thanks the solution worked for me!

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Comment by Aholicknight** [comment]
> hello

@Lucas-NN are you okay?

**Comment by xgqfrms** [comment]
> brew link nmap

not work?

![](https://img2022.cnblogs.com/blog/740516/202207/740516-20220714005510758-1041504262.png)

**Comment by NorseGaud** [comment]
None of the nmap solutions are my issue. Installing from brew today shows this same error. On macos 13.0.1
